<template>
  <section class="sb-section sb-section--soft features-section" id="features">
    <div class="sb-container">
      <div class="features-section__head">
        <p class="sb-eyebrow">Core capabilities</p>
        <h2 class="sb-section-title">The operational layer around local C++ development.</h2>
        <p class="sb-section-text">
          Softadastra Cloud focuses on records and access that teams need to keep shared C++ projects organized.
        </p>
      </div>

      <div class="features-section__grid">
        <article v-for="feature in features" :key="feature.title">
          <span>{{ feature.label }}</span>
          <h3>{{ feature.title }}</h3>
          <p>{{ feature.text }}</p>
        </article>
      </div>
    </div>
  </section>
</template>

<script setup>
const features = [
  {
    label: "Workspaces",
    title: "Workspaces and projects",
    text: "Organize related projects and team access inside shared workspaces.",
  },
  {
    label: "Packages",
    title: "Private packages and versions",
    text: "Publish and manage package metadata, version history, checksums, archives, visibility, and status.",
  },
  {
    label: "Lockfiles",
    title: "Lockfile records",
    text: "Upload and inspect vix.lock records used by linked projects.",
  },
  {
    label: "Reports",
    title: "Local build reports",
    text: "Store reports generated by local Vix.cpp builds, including target, profile, branch, commit, toolchain, duration, warnings, errors, and diagnostics.",
  },
  {
    label: "Access",
    title: "Members and permissions",
    text: "Manage workspace members, invitations, roles, access scopes, and project-level access.",
  },
  {
    label: "Tokens",
    title: "CLI and API tokens",
    text: "Create, inspect, and revoke access tokens for supported Cloud workflows.",
  },
];
</script>

<style scoped>
.features-section__head {
  max-width: 780px;
  margin-bottom: 30px;
}

.features-section__grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 12px;
}

.features-section__grid article {
  padding: 20px;
  border: 1px solid var(--sb-border);
  border-radius: var(--sb-radius-md);
  background: var(--sb-surface);
  box-shadow: var(--sb-shadow-sm);
}

.features-section__grid span {
  color: var(--sb-primary-hover);
  font-family: var(--sb-font-mono);
  font-size: 0.68rem;
  font-weight: 760;
  letter-spacing: 0.05em;
  text-transform: uppercase;
}

.features-section__grid h3 {
  margin-top: 12px;
  color: var(--sb-text);
  font-size: 1.05rem;
  letter-spacing: -0.015em;
}

.features-section__grid p {
  margin-top: 8px;
  color: var(--sb-text-soft);
  font-size: 0.92rem;
  line-height: 1.6;
}

@media (max-width: 980px) {
  .features-section__grid {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
}

@media (max-width: 640px) {
  .features-section__grid {
    grid-template-columns: 1fr;
  }
}
</style>
